# Platform checks to generate config.h
include ( CheckFunctionExists )
include ( CheckLibraryExists )
include ( CheckSymbolExists )
include ( CheckTypeSize )
include ( CheckIncludeFiles )

#set ( C_ALLOCA 1 )
#set ( ENABLE_NLS 1 )
set ( NDEBUG 1 )
#set ( NO_MINUS_C_MINUS_O 1 )
#set ( STACK_DIRECTION 1 )
set ( STDC_HEADERS 1 )
set ( TRE_APPROX 1 )
#set ( TRE_DEBUG 1 )
set ( TRE_MULTIBYTE 1 )
#set ( TRE_USE_ALLOCA 1 )
#set ( TRE_USE_SYSTEM_REGEX_H 1 )
set ( WCHAR_T_SIGNED 0 )
set ( WCHAR_T_UNSIGNED 0 )
#set ( _FILE_OFFSET_BITS 0 )
set ( _GNU_SOURCE 1 )
#set ( _LARGE_FILES 1 )
#set ( _REGCOMP_INTERNAL 1 )
set( TRE_REGEX_T_FIELD value )

# Headers
check_include_files ( alloca.h HAVE_ALLOCA_H )
check_include_files ( dlfcn.h HAVE_DLFCN_H )
check_include_files ( getopt.h HAVE_GETOPT_H )
check_include_files ( inttypes.h HAVE_INTTYPES_H )
check_include_files ( libutf8.h HAVE_LIBUTF8_H )
check_include_files ( memory.h HAVE_MEMORY_H )
check_include_files ( regex.h HAVE_REGEX_H )
check_include_files ( stdint.h HAVE_REG_ERRCODE_T )
check_include_files ( stdlib.h HAVE_STDLIB_H )
check_include_files ( strings.h HAVE_STRINGS_H )
check_include_files ( string.h HAVE_STRING_H )
check_include_files ( "sys/stat.h" HAVE_SYS_STAT_H )
check_include_files ( "sys/types.h" HAVE_SYS_TYPES_H )
check_include_files ( unistd.h HAVE_UNISTD_H )
check_include_files ( wchar.h HAVE_WCHAR_H )
check_include_files ( wctype.h HAVE_WCTYPE_H )

# Types
check_type_size ( mbstate_t HAVE_MBSTATE_T )
check_type_size ( reg_errcode_t HAVE_REG_ERRCODE_T )
check_type_size ( wchar_t HAVE_WCHAR_T )
check_type_size ( wint_t HAVE_WINT_T )

# Functions
check_function_exists ( alloca HAVE_ALLOCA )
check_function_exists ( CFLocaleCopyCurrent HAVE_CFLOCALECOPYCURRENT )
check_function_exists ( CFPreferencesCopyAppValue HAVE_CFPREFERENCESCOPYAPPVALUE )
check_function_exists ( dcgettext HAVE_DCGETTEXT )
check_function_exists ( getopt_long HAVE_GETOPT_LONG )
check_function_exists ( gettext HAVE_GETTEXT )
check_function_exists ( iconv HAVE_ICONV )
check_function_exists ( isascii HAVE_ISASCII )
check_function_exists ( isblank HAVE_ISBLANK )
check_function_exists ( iswascii HAVE_ISWASCII )
check_function_exists ( iswblank HAVE_ISWBLANK )
check_function_exists ( iswctype HAVE_ISWCTYPE )
check_function_exists ( iswlower HAVE_ISWLOWER )
check_function_exists ( iswupper HAVE_ISWUPPER )
check_function_exists ( mbrtowc HAVE_MBRTOWC )
check_function_exists ( mbtowc HAVE_MBTOWC )
check_function_exists ( towlower HAVE_TOWLOWER )
check_function_exists ( towupper HAVE_TOWUPPER )
check_function_exists ( wcschr HAVE_WCSCHR )
check_function_exists ( wcscpy HAVE_WCSCPY )
check_function_exists ( wcslen HAVE_WCSLEN )
check_function_exists ( wcsncpy HAVE_WCSNCPY )
check_function_exists ( wcsrtombs HAVE_WCSRTOMBS )
check_function_exists ( wcstombs HAVE_WCSTOMBS )
check_function_exists ( wctype HAVE_WCTYPE )
