version: 1.0.{build}

shallow_clone: true

environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"
  - LUA: "luajit 2.0"
  - LUA: "luajit 2.1"

before_build:
  - set PATH=%CD%\here\bin;C:\Python27\Scripts;%PATH%
  - pip install hererocks

build_script:
  - hererocks here --%LUA% -r latest
  - luarocks make
  - luarocks install busted

test_script: busted
